sonar.projectKey=YasiruNil_portfolio
sonar.organization=yasirunil
sonar.projectName=portfolio

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/__mocks__/**
sonar.sourceEncoding=UTF-8