name: Deploy to Development
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: |
          echo "CLONING REPOSITORY"
          git clone git@github.com:username/${{github.repository}}.git myFiles
          cd myFiles && ls

  